use utoipa::OpenApi;

#[derive(OpenApi)]
#[openapi(
    paths(
        crate::http::healthz,
        crate::http::openapi_json,
        crate::http::admin::targets::list,
        crate::http::admin::targets::create,
        crate::http::admin::targets::update,
        crate::http::admin::targets::delete,
        crate::http::admin::rules::list,
        crate::http::admin::rules::create,
        crate::http::admin::rules::update,
        crate::http::admin::rules::delete,
        crate::http::admin::rules::test,
        crate::http::admin::templates::list,
        crate::http::admin::templates::create,
        crate::http::admin::templates::update,
        crate::http::admin::templates::delete,
        crate::http::admin::logs::list,
        crate::http::admin::logs::detail,
        crate::http::admin::logs::purge,
        crate::http::admin::logs::delete,
        crate::http::admin::config::export_config,
        crate::http::admin::config::import_config
    ),
    components(schemas(
        crate::domain::Target,
        crate::domain::Rule,
        crate::domain::SequenceStep,
        crate::domain::RuleAction,
        crate::domain::RuleMatcher,
        crate::domain::StringMatcher,
        crate::domain::BodyMatcher,
        crate::domain::ResponseTemplate,
        crate::domain::RequestLog,
        crate::domain::MessageSnapshot,
        crate::domain::LogDetail,
        crate::http::types::TargetPayload,
        crate::http::types::RulePayload,
        crate::http::types::SequenceStepPayload,
        crate::http::types::RuleTestPayload,
        crate::http::types::TemplatePayload,
        crate::http::types::IdResponse,
        crate::http::types::TargetPage,
        crate::http::types::RulePage,
        crate::http::types::TemplatePage,
        crate::http::types::LogPage,
        crate::http::types::PurgeResponse,
        crate::domain::RuleTestResult,
        crate::domain::RenderedPreview,
        crate::domain::ExportBundle,
        crate::domain::ImportSummary
    ))
)]
pub struct ApiDoc;
